In [64]:
from src.goal_functions import ackley
import numpy as np

In [65]:
print(xs)
ackley(xs)
XD = np.random.uniform(low=-1, high=1, size=[1,3])
print(XD)

NameError: name 'xs' is not defined

In [115]:
from src.goal_functions import ackley
import numpy as np


class EA:
    def __init__(self, specimen_size, offspring_size, population_size, num_iterations):
        self.specimen_size = specimen_size
        self.offspring_size = offspring_size
        self.population_size = population_size
        self.num_iterations = num_iterations

    def population(self):
        return np.random.uniform(low=-10, high=10, size=[self.population_size + self.offspring_size, self.specimen_size])

    def results_fun(self, population):
        return np.array([ackley(x) for x in population])

    def combination(self, xs, ys):
        return (xs + ys)/2

    def mutation(self, xs):
        return xs + np.random.uniform(low=-1, high=1, size=len(xs))

    def mutation_2(xs):
        return xs + 1 #sposoby mutacji

    def algorithm(self):
        population = self.population()
        results = self.results_fun(population)
        for _ in range(self.num_iterations):
            for i in range(self.offspring_size):
                a, b = np.random.randint(low=0, high = self.population_size - 1, size=2)
                child = self.combination(population[a], population[b])
                child = self.mutation(child)
                population[i+self.population_size] = child
                results[i+self.population_size] = ackley(population[i+self.population_size])

            indicies = np.argsort(results)
            population = population[indicies]
            results = results[indicies]
        return results, population

    
north_sentinel = EA(3, 10, 10, 10000) #specimen_size, offspring_size, population_size, num_iterations
results, population = north_sentinel.algorithm()








In [116]:


print(population)
print()
print(results)

[[-2.11160279e-02  1.37242326e-02 -5.47010906e-03]
 [ 2.73604246e-02  1.74540604e-02  3.80431067e-03]
 [-1.00599983e-02 -3.05788091e-02  8.90710936e-03]
 [ 2.53563239e-02  2.24958648e-02  6.59372672e-03]
 [-1.76404527e-02 -1.47786036e-02 -2.58374748e-02]
 [-1.65941836e-02  2.20359005e-02  2.61871017e-02]
 [-2.81210115e-02 -2.80954929e-02  3.20289419e-03]
 [ 1.43618801e-02 -3.77530873e-02 -6.31709403e-03]
 [ 3.72234970e-02  1.86397802e-02 -4.90803800e-04]
 [-1.76826378e-02 -3.11342939e-02  2.88002973e-02]
 [ 1.07795845e-01 -1.93006411e-01  4.85189794e-01]
 [-1.83650705e-01  5.77028922e-01  1.88547796e-01]
 [-5.92782174e-01  4.53552463e-01  1.29378372e-01]
 [ 6.91878415e-02  6.25089317e-01 -8.45895889e-01]
 [-8.79147615e-01 -8.42414175e-01 -9.65988280e-01]
 [ 2.54182037e-01  7.06002017e-01 -9.35070281e-01]
 [ 4.47714378e-01  3.24771524e-01 -9.67935975e-01]
 [ 8.23037491e-01 -4.01202480e-01 -8.42757527e-01]
 [-4.21999686e-01  7.75590833e-01 -7.95805416e-01]
 [ 5.96493207e-01 -7.09902473e-

In [24]:
indicies

array([ 0,  8,  7,  6,  5,  9,  3,  2,  1,  4, 15, 17, 13, 19, 14, 10, 18,
       11, 12, 16])